execute post-release hook

diff --git a/git-release b/git-release
--- a/git-release
+++ b/git-release
@@ -23,4 +23,17 @@ if [[ $? != 0 ]]; then
 fi
 
 git tag -a $NEXT_VERSION -m "$MESSAGE"
+if [[ $? != 0 ]]; then
+    echo "couldn't tag"
+    exit 1
+fi
+
 echo $NEXT_VERSION
+
+GITROOT="$(git rev-parse --show-toplevel)"
+GIT_HOOK_POST_RELEASE=$GITROOT/.git/hooks/post-release
+
+if [ -f "$GIT_HOOK_POST_RELEASE" ]; then
+    $GIT_HOOK_POST_RELEASE
+fi
+
