fail if curl fails

diff --git a/git-release b/git-release
--- a/git-release
+++ b/git-release
@@ -38,8 +38,6 @@ git push --follow-tags
 
 echo "$NEXT_VERSION"
 
-git hook post-release "$NEXT_VERSION" "$LAST_VERSION"
-
 
 BODY="Release of version $NEXT_VERSION"
 if [[ -n "$MESSAGE" ]]; then
@@ -51,12 +49,15 @@ REF="master"
 GIT_HOST=$(git host)
 if [[ "$GIT_HOST" == "github.com" && -n "$GITHUB_TOKEN" ]]; then
     REPO=$(git name)
-    DATA='{"tag_name": "'$NEXT_VERSION'", "target_commitish": "'$REF'", "name": "'$NAME'", "body": "'$BODY'", "draft": false, "prerelease": false}'
-    curl --request POST \
+    DATA='{"tag_name":"'$NEXT_VERSION'","target_commitish":"'$REF'","name":"'$NAME'","body":"'$BODY'","draft":false,"prerelease":false}'
+    if ! curl --fail --request POST \
         --url "https://api.github.com/repos/$REPO/releases" \
-        --header "Content-Type: application/json" \
+        --header "Accept: application/vnd.github.v3+json" \
         --header "Authentication: token $GITHUB_TOKEN" \
-        --data "$DATA"
+        --data "$DATA"; then
+        echo "failed to create github release"
+        exit 2
+    fi
 elif [[ "$GIT_HOST" == "gitlab.com" && -n "$GITLAB_TOKEN" ]]; then
     if [[ -n "$GITLAB_PROJECT_ID" ]]; then
         echo "Missing GITLAB_PROJECT_ID environment variable"
@@ -64,9 +65,16 @@ elif [[ "$GIT_HOST" == "gitlab.com" && -n "$GITLAB_TOKEN" ]]; then
     fi
     DATA='{"name": "'$NAME'", "tag_name": "'$NEXT_VERSION'", "description": "'$BODY'", "ref": "'$REF'" }'
     URL="https://gitlab.com/api/v4/projects/$PROJECT_ID/releases"
-    curl --request POST \
+    if ! curl --fail --request POST \
         --url "$URL" \
+        --header "Accept: application/vnd.github.v3+json" \
         --header "Content-Type: application/json" \
         --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
-        --data "$DATA"
+        --data "$DATA"; then
+        echo "failed to create gitlab release"
+        exit 2
+    fi
 fi
+
+git hook post-release "$NEXT_VERSION" "$LAST_VERSION"
+
